name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    
    - run: cd Frontend

    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
          username: 'Haloen'
          reponame: 'CS6131'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
